=== JNArrazola/XML-DTD_Parser/example/detede.dtd
<!ELEMENT table (name, columns)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT columns (column+)>
<!ELEMENT column (name, type, length?, constraints?)> 
<!ELEMENT type (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT constraints (constraint*)>
<!ELEMENT constraint (#PCDATA)>

=== JNArrazola/XML-DTD_Parser/example/table.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "detede.dtd">

<table>
  <name>users</name>
  <columns>
    <column>
      <name>id</name>
      <type>integer</type>
      <length>11</length>
      <constraints>
        <constraint>primary key</constraint>
        <constraint>not null</constraint>
      </constraints>
    </column>
    <column>
      <name>username</name>
      <type>varchar</type>
      <length>255</length>
      <constraints>
        <constraint>unique</constraint>
        <constraint>not null</constraint>
      </constraints>
    </column>
    <column>
      <name>email</name>
      <type>varchar</type>
      <length>255</length>
      <constraints>
        <constraint>not null</constraint>
      </constraints>
    </column>
  </columns>
</table>
