=== JNArrazola/XML-DTD_Parser/example/exampleDTD.dtd
<!ELEMENT table (name, columns, constraints) >
<!ELEMENT name (#PCDATA)>
<!ELEMENT columns (column+)>
<!ELEMENT column (name, type, primary_key?, default?, check?, constraints?)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT check (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT primary_key (#PCDATA)>
<!ELEMENT constraints (constraint+)>
<!ELEMENT constraint (#PCDATA)>

<!ATTLIST check condition CDATA #REQUIRED>

=== JNArrazola/XML-DTD_Parser/example/estesi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "exampleDTD.dtd">

<table>
    <name>USERS</name>
    <columns>
        <column>
            <name>ID</name>
            <type>NUMBER</type>
            <primary_key>TRUE</primary_key>
            <constraints>
                <constraint>NOT NULL</constraint>
            </constraints>
        </column>
        <column>
            <name>USERNAME</name>
            <type>STRING</type>
            <check condition="LENGTH(USERNAME) > 3"/>
            <constraints>
                <constraint>UNIQUE</constraint>
                <constraint>NOT NULL</constraint>
                <!-- here cannot be a foreing key, primary key or default constraint -->
            </constraints>
        </column>
        <column>
            <name>EMAIL</name>
            <type>STRING</type>
            <default>NULL</default>
            <constraints>
                <constraint>UNIQUE</constraint>
                <constraint>NOT NULL</constraint>
            </constraints>
        </column>
    </columns>
    <constraints>
        <constraint>FOREIGN KEY (ID) REFERENCES USERS(ID)</constraint>
        <!-- here cannot be a NOT NULL or DEFAULT constraint -->
    </constraints>
</table>
